#!/usr/bin/env bash

set -eu

EMACS="${EMACS:-${HOME}/src/emacs/src/emacs}"

if [[ $# -eq 0 ]]; then
	echo "usage: $0 TMPDIR [OPTION-OR-FILENAME]..." >&2
	exit 2
fi

tmpdir=$1
shift

if [[ ! -d ${tmpdir} ]]; then
	mkdir "${tmpdir}"
	(echo ';;; -*- lexical-binding: t -*-'; \
	 echo '(fido-mode)') \
		> "${tmpdir}/init.el"
fi

${EMACS} --init-directory="${tmpdir}" \
	 --no-site-file \
	 --no-site-lisp \
	 --no-splash \
	 --no-x-resources \
	 "$@"
