#!/usr/bin/env bash

set -eu

EMACS="${EMACS:-${HOME}/src/emacs/src/emacs}"

if [[ $# -eq 0 ]]; then
	echo "usage: $0 INIT-DIRECTORY [OPTION-OR-FILENAME]..." >&2
	exit 2
fi

initdir=$1
shift

if [[ ! -d ${initdir} ]]; then
	mkdir "${initdir}"
	(echo ';;; -*- lexical-binding: t -*-'; \
	 echo '(fido-mode)') \
		> "${initdir}/init.el"
fi

${EMACS} --init-directory="${initdir}" \
	 --no-site-file \
	 --no-site-lisp \
	 --no-splash \
	 --no-x-resources \
	 "$@"
