#!/bin/bash

set -e -u

LAST_CTX_FILE="${HOME}/.kctx_last"

get_last_ctx ()
{
	if [[ ! -r $LAST_CTX_FILE ]]; then
		echo 'error: unknown last context' >&2
		return 1
	fi

	last_ctx=$(cat "$LAST_CTX_FILE")
	if [[ -z $last_ctx ]]; then
		echo 'error: empty last context' >&2
		return 1
	fi

	echo $last_ctx
}

if [[ $# != 1 ]]; then
	kubectl config get-contexts
	exit
fi

if [[ $1 == "-" ]]; then
	last_ctx=$(get_last_ctx)
	cur_ctx=$(kubectl config current-context)
	kubectl config use-context "$last_ctx"
	echo $cur_ctx > "$LAST_CTX_FILE"
	exit
fi

kubectl config current-context > "$LAST_CTX_FILE"
kubectl config use-context "$1"
